device: cuda

# where the weights are located for build time
system_model_path: /ml/models/logo

storage:
  # where the weights are found at runtime
  weights: weights
runtime:
  default:
    fps: 4
    allow_single_frame: false
inference:
  # general:
  inference_type: "r"
  input_type: "video"
  input_path: "/home/elv-zhounan/elv-ml/brand/v2/test/videos/demo.mp4"
  save_dir: "./test/main_res"
  # model:
  yolo_cfg: "yolo/yolov5s_c2.yaml"
  yolo_weights: "yolo/yolo5s_c2_weights.pt"
  resnext_weights: "resnext/160.ckpt"
  num_classes: 2465
  c_logo_label_map: "resnext/logo_label_map.json"
  r_feature_pool: "resnext/feature_pool/feature_pool.npy"
  r_labels: "resnext/feature_pool/cropped_pool_labels.json"
  r_classes: "resnext/feature_pool/cropped_pool_classes.json"
  r_imagenames: "resnext/feature_pool/cropped_pool_images.json"
  # thres:
  detect_thres: 0.05
  nms_iou_thres: 0.4
  classify_thres: 0.7
  retrieval_thres: 0.95
  eval_iou_thres: 0.5
  retrieval_intervel: -1
  enlarge_bbox_ratio: 1.0
  # mask
  mask_file: "mask_brands.json"